import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import code from "../public/dev-ed-wave.png";
import deved from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.jpeg";
import web2 from "../public/web2.jpeg";
import web3 from "../public/web3.jpeg";
import web4 from "../public/web4.jpeg";
import web5 from "../public/web5.jpeg";
import web6 from "../public/web6.jpeg";
import web7 from "../public/web7.jpeg";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Developed By </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
             Muhammad Amaris Nagori 
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Full-Stack Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            A passionate and innovative software engineer who has most prime focus on programming and scripting , Understanding of clients and customer bussiness , Databases , Cloud computing , Source control , Testing and Security of the software
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <AiFillTwitterCircle />
              <AiFillLinkedin />
              <AiFillYoutube />
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Details of My Work</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance
              developer, I have done both onsite and remote work for
              <span className="text-teal-500"> US Based Companies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with one of the most talanted people to create digital products
              for both business and consumer use. Which Includes E-commerce sites , Management systems for universities and offices and for transaction apps
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including website development , Dekstop applications and IOS/Android Applications
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Front End
              </h3>
              <p className="py-2">
              Creating the websites, Dekstop applications , Mobile apps for Android and Ios 
              </p>
              <h4 className="py-4 text-teal-600">Dev Techs I used</h4>
              <p className="text-gray-800 py-1">React JS
              </p>
              <p className="text-gray-800 py-1">              Gatsby JS
              </p>
              <p className="text-gray-800 py-1">Next js</p>
              <p className="text-gray-800 py-1">              Three JS
              </p>
              <p className="text-gray-800 py-1"> React-Native 
              </p>
              <p className="text-gray-800 py-1">Electron JS
              </p>

            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
              -- For Backend (Rest APIs)</h3>
             
              <h4 className="py-4 text-teal-600"> Dev Techs I use for development of Backened
              </h4>
              <p className="text-gray-800 py-1">Node JS</p>
              <p className="text-gray-800 py-1">Django</p>

            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">DataBases / Deployments</h3>
              <p className="py-2">
              For Databases / Deploying
              </p>
              <h4 className="py-4 text-teal-600">               Dev Techs for the Data Base and back end deployment 
              </h4>
              <p className="text-gray-800 py-1">Mongo DB</p>
              <p className="text-gray-800 py-1">FireBase</p>
              <p className="text-gray-800 py-1">SQL</p>
              <p className="text-gray-800 py-1">AWS services </p>
              <p className="text-gray-800 py-1">Microsoft Azure services </p>
              <p className="text-gray-800 py-1">Cloud Computing </p>
              <p className="text-gray-800 py-1">Cloud Data security </p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
            <Image 
            src={web1}
            style={{width:'300px',height:'300px'}}
            />
            </div>
            <div className="basis-1/3 flex-1">
            <Image 
            src={web2}
            style={{width:'300px',height:'300px'}}
            />
            </div>
            <div className="basis-1/3 flex-1">
            <Image 
            src={web3}
            style={{width:'300px',height:'300px'}}
            />
            </div>
            <div className="basis-1/3 flex-1">
            <Image 
            src={web4}
            style={{width:'300px',height:'300px'}}
            />
            </div>
            <div className="basis-1/3 flex-1">
            <Image 
            src={web5}
            style={{width:'300px',height:'300px'}}
            />
            </div>
            <div className="basis-1/3 flex-1">
            <Image 
            src={web6}
            style={{width:'300px',height:'300px'}}
            />
            </div>
            <div className="basis-1/3 flex-1">
            <Image 
            src={web7}
            style={{width:'300px',height:'300px'}}
            />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
